WITH COMPLETED_SALES AS (
    SELECT
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM
        USED_GOODS_BOARD
    WHERE
        STATUS = 'DONE'
    GROUP BY
        WRITER_ID
    HAVING
        SUM(PRICE) >= 700000
)
SELECT
    u.USER_ID,
    u.NICKNAME,
    c.TOTAL_SALES
FROM
    COMPLETED_SALES c
JOIN
    USED_GOODS_USER u
ON
    c.WRITER_ID = u.USER_ID
ORDER BY
    c.TOTAL_SALES;