WITH YEARLY_MAX AS (
    SELECT
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY
        YEAR
),
DEV_DATA AS (
    SELECT
        e.ID,
        EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) AS YEAR,
        y.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV
    FROM
        ECOLI_DATA e
    JOIN
        YEARLY_MAX y
    ON
        EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) = y.YEAR
)
SELECT 
    YEAR,
    YEAR_DEV,
    ID
FROM 
    DEV_DATA
ORDER BY
    YEAR,
    YEAR_DEV;
