WITH MAX_FISH AS (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM 
        FISH_INFO
    GROUP BY
        FISH_TYPE
)
SELECT 
    ID, 
    FISH_NAME, 
    LENGTH
FROM 
    FISH_INFO FI
JOIN
    MAX_FISH MF
    ON FI.FISH_TYPE = MF.FISH_TYPE AND FI.LENGTH = MF.MAX_LENGTH
JOIN
    FISH_NAME_INFO NI
    ON FI.FISH_TYPE = NI.FISH_TYPE
ORDER BY FI.ID;